DROP DATABASE EJEMPLO_011;
CREATE DATABASE EJEMPLO_011;
USE EJEMPLO_011;
	
 CREATE TABLE `DEPARTAMENTO` (  
`NUMDEPTO` int (5) AUTO_INCREMENT,  
`NOMDEPTO` varchar (100) DEFAULT NULL,  
`UBICACIONDPTO` varchar (100) DEFAULT NULL,  
PRIMARY KEY (`NUMDEPTO`)
);

CREATE TABLE `EMPLEADO` (  
`NUMEMPLEADO` int (5) AUTO_INCREMENT,  
`NOMBRE` varchar (100) DEFAULT NULL,  
`NUMDEPTO` int (5) DEFAULT NULL,  
PRIMARY KEY (`NUMEMPLEADO`)
);

CREATE TABLE `USUARIOS_ADMIN` (  
`IDUSUARIO` int (5) AUTO_INCREMENT,  
`CORREO` varchar (100) DEFAULT NULL,  
`PASS` varchar (100) DEFAULT NULL, 
`PRIMER_NOMBRE` varchar (100) DEFAULT NULL, 
`APELLIDO` varchar (100) DEFAULT NULL,  
PRIMARY KEY (`IDUSUARIO`)
);

ALTER TABLE EMPLEADO ADD CONSTRAINT DEP_EMPLEADO FOREIGN KEY (NUMDEPTO) REFERENCES DEPARTAMENTO (NUMDEPTO);

INSERT INTO USUARIOS_ADMIN VALUES(001, 'admin@correo.cl','123','RAMON','VASQUEZ');

INSERT INTO DEPARTAMENTO VALUES(null,'INFORMATICA','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'REDES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'PARTES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'SALUD','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'BIENESTAR','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'ASEO Y ORNATO','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'CONTABILIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(null,'RRHH','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(null,'ASEO Y ORNATO','ARGENTINA');
INSERT INTO DEPARTAMENTO VALUES(null,'CONTABILIDAD','BOLIVIA');
INSERT INTO DEPARTAMENTO VALUES(null,'RRHH','MEXICO');
INSERT INTO DEPARTAMENTO VALUES(null,'CARRETE','CHILE');
INSERT INTO DEPARTAMENTO VALUES(null,'SEGURIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(null,'MARKETING','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(null,'MECANICA','CHILE');



INSERT INTO EMPLEADO VALUES (null,'Matias Zarate', 15);
INSERT INTO EMPLEADO VALUES (null,'Felipe Perez', 15);
INSERT INTO EMPLEADO VALUES (null,'Bob Marley', 15);
INSERT INTO EMPLEADO VALUES (null,'Pedro Polanco', 15);
INSERT INTO EMPLEADO VALUES (null,'Eduardo Azul', 15);
INSERT INTO EMPLEADO VALUES (null,'Oscar Fernandez', 14);
INSERT INTO EMPLEADO VALUES (null,'Maria Jose Velasquez', 14);
INSERT INTO EMPLEADO VALUES (null,'Fernanda Parra', 14);
INSERT INTO EMPLEADO VALUES (null,'Teresa Valdez', 14);
INSERT INTO EMPLEADO VALUES (null,'Ignacio MacGreg', 14);
INSERT INTO EMPLEADO VALUES (null,'Rodrigo Zarabia', 13);
INSERT INTO EMPLEADO VALUES (null,'Marcelo Zapata', 13);
INSERT INTO EMPLEADO VALUES (null,'Mark Jeres', 13);
INSERT INTO EMPLEADO VALUES (null,'Cristian Aguirre', 13);
INSERT INTO EMPLEADO VALUES (null,'Julian Martel', 13);
INSERT INTO EMPLEADO VALUES (null,'Kilos Demetrio', 12);
INSERT INTO EMPLEADO VALUES (null,'Astorga Daniel', 12);
INSERT INTO EMPLEADO VALUES (null,'Yeny Marlen', 12);
INSERT INTO EMPLEADO VALUES (null,'Julia Zapata', 12);
INSERT INTO EMPLEADO VALUES (null,'Esteban Cerrado', 12);
INSERT INTO EMPLEADO VALUES (null,'Kilos Demetrio Azul', 11);
INSERT INTO EMPLEADO VALUES (null,'Pablo Carmona', 11);
INSERT INTO EMPLEADO VALUES (null,'Ramon Vicencio', 11);
INSERT INTO EMPLEADO VALUES (null,'Julia Veracruz', 11);
INSERT INTO EMPLEADO VALUES (null,'Joaquin Mendez', 11);
INSERT INTO EMPLEADO VALUES (null,'Ricardo Abrilar', 10);
INSERT INTO EMPLEADO VALUES (null,'Rocio Vicencio', 10);
INSERT INTO EMPLEADO VALUES (null,'Bianca Vicencio', 10);
INSERT INTO EMPLEADO VALUES (null,'Graciela LLancavil', 10);
INSERT INTO EMPLEADO VALUES (null,'Enrique Carmona', 10);
INSERT INTO EMPLEADO VALUES (null,'Nora Allen', 9);
INSERT INTO EMPLEADO VALUES (null,'Ramon Cisco', 9);
INSERT INTO EMPLEADO VALUES (null,'Frank Martin', 9);
INSERT INTO EMPLEADO VALUES (null,'Milena Snow', 9);
INSERT INTO EMPLEADO VALUES (null,'Ruth Vitis', 9);
INSERT INTO EMPLEADO VALUES (null,'Sol Marisol', 8);
INSERT INTO EMPLEADO VALUES (null,'Jorge Carmona', 8);
INSERT INTO EMPLEADO VALUES (null,'Miguel Mac', 8);
INSERT INTO EMPLEADO VALUES (null,'Rafael Alarcon', 8);
INSERT INTO EMPLEADO VALUES (null,'Ruth Vitis', 8);
INSERT INTO EMPLEADO VALUES (null,'Jhon Nieve', 7);
INSERT INTO EMPLEADO VALUES (null,'Martin Escoses', 7);
INSERT INTO EMPLEADO VALUES (null,'Alex Citrico', 7);
INSERT INTO EMPLEADO VALUES (null,'Marcelo de Cachureos', 7);
INSERT INTO EMPLEADO VALUES (null,'Alfonso Mastil', 7);
INSERT INTO EMPLEADO VALUES (null,'Juan Quiñones', 6);
INSERT INTO EMPLEADO VALUES (null,'Adamiro Rojas', 6);
INSERT INTO EMPLEADO VALUES (null,'Fernando Maciel', 6);
INSERT INTO EMPLEADO VALUES (null,'Carolina Merlot', 6);
INSERT INTO EMPLEADO VALUES (null,'Casandra Parra', 6);
INSERT INTO EMPLEADO VALUES (null,'Salomon Clavel', 5);
INSERT INTO EMPLEADO VALUES (null,'Quiste Martes', 5);
INSERT INTO EMPLEADO VALUES (null,'Carlos Zaul', 5);
INSERT INTO EMPLEADO VALUES (null,'Eduardo Bomvalet', 5);
INSERT INTO EMPLEADO VALUES (null,'Arturo Prat', 5);
INSERT INTO EMPLEADO VALUES (null,'Maria Jose Pinganilla', 4);
INSERT INTO EMPLEADO VALUES (null,'Carlonia Marsobia', 4);
INSERT INTO EMPLEADO VALUES (null,'Jose Jose', 4);
INSERT INTO EMPLEADO VALUES (null,'Esternon Peres', 4);
INSERT INTO EMPLEADO VALUES (null,'Ivon Cadiz', 4);
INSERT INTO EMPLEADO VALUES (null,'Moscard Trek', 3);
INSERT INTO EMPLEADO VALUES (null,'Hugo Luis Merc', 3);
INSERT INTO EMPLEADO VALUES (null,'Casimiro Lavaca', 3);
INSERT INTO EMPLEADO VALUES (null,'Aston Gonzalez', 3);
INSERT INTO EMPLEADO VALUES (null,'Crecencio Fretere', 3);
INSERT INTO EMPLEADO VALUES (null,'Juan Pedro Pazola', 2);
INSERT INTO EMPLEADO VALUES (null,'Roquefort Martin', 2);
INSERT INTO EMPLEADO VALUES (null,'Carlos Espertes', 2);
INSERT INTO EMPLEADO VALUES (null,'Jino Janos', 2);
INSERT INTO EMPLEADO VALUES (null,'Ether Certero', 2);
INSERT INTO EMPLEADO VALUES (null,'Pepe Grillo', 1);
INSERT INTO EMPLEADO VALUES (null,'Marisol Luna', 1);
INSERT INTO EMPLEADO VALUES (null,'Pedro Cortisona', 1);
INSERT INTO EMPLEADO VALUES (null,'Eugenio Mundial', 1);
INSERT INTO EMPLEADO VALUES (null,'Nelson Gertred', 1);